server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: tiger
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 10
